---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  /api/v1/auth/sign_in:
    post:
      tags:
        - Authentication
      summary: Signs in a user
      description: Use this endpoint to authenticate a user.
      operationId: signInUser
      parameters:
        - name: email
          in: query
          required: true
          schema:
            type: string
            example: test@test.com
        - name: password
          in: query
          required: true
          schema:
            type: string
            example: password
      responses:
        "200":
          description: successful
        "401":
          description: unauthorized
  /api/v1/auth/sign_out:
    delete:
      tags:
        - Authentication
      summary: Signs out a user
      description: Use this endpoint to sign out a user. Before it please sign in User with post request. Use its uid, client and access-token and try to sign out
      operationId: signOutUser
      parameters:
        - name: uid
          in: header
          required: true
          schema:
            type: string
            example: test@test.com
        - name: client
          in: header
          required: true
          schema:
            type: string
            example: 6xXSSR5Rh1inF305K-V_kg
        - name: access-token
          in: header
          required: true
          schema:
            type: string
            example: pFppqIdXa58uHkAZ0kXRqw
      responses:
        '200':
          description: Successful sign out
        '401':
          description: Unauthorized
  /api/v1/auth:
    post:
      tags:
        - Authentication
      summary: Signs up a user
      description: Use this endpoint to create a new user.
      operationId: signUpUser
      parameters:
        - name: email
          in: query
          required: true
          schema:
            type: string
            example: test2@test.com
        - name: password
          in: query
          required: true
          schema:
            type: string
            example: password
        - name: password_confirmation
          in: query
          required: true
          schema:
            type: string
            example: password
      responses:
        "200":
          description: successful
        "422":
          description: unprocessable content